mongo:
#  线上正式
  app:
    host: "192.168.10.3"
    port: 27017
    username: "root"
    password: "123456"
    authSource: "app"
    maxPoolSize: 10
# 测试环境
  app_test:
    host: "192.168.10.3"
    port: 27017
    username: "root"
    password: "123456"
    authSource: "app_test"
    maxPoolSize: 2

# 每日信息
  day_db:
    host: "192.168.10.3"
    port: 27017
    username: "root"
    password: "123456"
    authSource: "day"
    maxPoolSize: 2